# Site settings
title: Welcome BackPack
email: Joseph@corestaffing.us
descrption: > # this means to ignore newlines until "baseurl:"
welcomebackpack will provide a BackPack full of hope to returning citizens.
baseurl: "/home/" # the subpath of your site, e.g. /blog/
url: "www.welcomebackpack.com" # the base hostname & protocol for your site

# User setting
owner: Joseph Cureton
email: josephcureton1@gmail.com
facebook_username:
twitter_username:
github_username: josephcureton
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: 443.704.4635
copyright:

# API settings
google_api_key: AIzaSyDo8aGumixeS-7ini7m5J6JHXSmH_bCm-A

# Build settings
markdown: kramdown