# Site settings
<<<<<<< HEAD
title: Welcome BackPack
email: Joseph@corestaffing.us
descrption: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://josephcureton.github.io/welcome-back-pack" # the base hostname & protocol for your site

# User setting
owner: Joseph Cureton
email: josephcureton1@gmail.com
facebook_username:
twitter_username:
github_username: josephcureton
address:
  - line: "10 East North Ave Suite 500" 
  - line: "Baltinore Maryland 21202"
  # Feel free to add more lines here 
telephone: 443.704.4635
copyright:

# API settings
google_api_key: AIzaSyDo8aGumixeS-7ini7m5J6JHXSmH_bCm-A
=======
title: Stylish Portfolio
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# User setting
owner: Start Bootstrap
email: name@example.com
facebook_username: example
twitter_username: example
github_username: example
address:
  - line: 3481 Melrose Hill St
  - line: "Los Angeles, CA 90029"
  # Feel free to add more lines here 
telephone: (123) 456-7890
copyright: Your Site

# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ
>>>>>>> origin/gh-pages

# Build settings
markdown: kramdown